import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, randomBytes, sign } from "node:crypto";
import type { AddressInfo } from "node:net";
import { test } from "node:test";
import express from "express";
import cookieSession from "cookie-session";
import { isoCBOR } from "@simplewebauthn/server/helpers";

test("account security protects login, passkey enrollment and factor recovery", async t => {
  process.env.DATABASE_PATH = ":memory:";
  process.env.SESSION_SECRET = "isolated-security-test-secret-at-least-32-characters";
  process.env.PUBLIC_URL = "http://localhost:3000";
  const { db, runMigrations } = await import("../src/db/index.js");
  const { authRouter } = await import("../src/api/auth.js");
  const { createUser } = await import("../src/auth/users.js");
  const security = await import("../src/auth/security.js");
  const { createPersonalAccessToken, resolveToken } = await import("../src/auth/tokens.js");
  runMigrations();
  // Expiry, attempt budget, purpose, version and client binding apply before a factor is checked.
  const isolated = createUser({ email: "challenge@example.test", password: "challenge test password", displayName: "Challenge", role: "user" });
  security.securityAccount(isolated.id);
  const handle = security.issueSecurityChallenge("mfa", isolated.id, "native-login", {});
  assert.equal(security.readSecurityChallenge(handle, "mfa", "web-login"), null);
  assert.equal(security.readSecurityChallenge(handle, "reauth", "native-login"), null);
  for (let attempt = 0; attempt < 5; attempt++) assert.ok(security.readSecurityChallenge(handle, "mfa", "native-login"));
  assert.equal(security.readSecurityChallenge(handle, "mfa", "native-login"), null);
  const expired = security.issueSecurityChallenge("mfa", isolated.id, "native-login", {}, -1);
  assert.equal(security.readSecurityChallenge(expired, "mfa", "native-login"), null);
  const outdated = security.issueSecurityChallenge("mfa", isolated.id, "native-login", {});
  security.revokeSecuritySessions(isolated.id);
  assert.equal(security.readSecurityChallenge(outdated, "mfa", "native-login"), null);
  const password = "test password long enough";
  const user = createUser({ email: "security@example.test", password, displayName: "Reader", role: "user" });
  const other = createUser({ email: "other@example.test", password, displayName: "Other", role: "user" });
  const app = express();
  app.use(express.json());
  app.use(cookieSession({ name: "test", secret: process.env.SESSION_SECRET }));
  app.use("/api/auth", authRouter);
  const server = app.listen(0);
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api/auth`;
  t.after(() => { server.closeAllConnections(); server.close(); db.close(); });
  let cookie = "";
  const call = async (path: string, body?: unknown, overrides: { cookie?: string; token?: string; method?: string; origin?: string } = {}) => {
    const headers: Record<string, string> = { "content-type": "application/json", origin: overrides.origin ?? "http://localhost:3000" };
    if (overrides.token) headers.authorization = `Bearer ${overrides.token}`;
    else headers.cookie = overrides.cookie ?? cookie;
    const response = await fetch(base + path, { method: overrides.method ?? (body === undefined ? "GET" : "POST"), headers, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
    const updated = response.headers.getSetCookie().map(value => value.split(";")[0]).join("; ");
    if (updated && overrides.cookie === undefined && !overrides.token) cookie = updated;
    return { status: response.status, body: response.status === 204 ? null : await response.json(), updated };
  };
  const login = () => call("/login", { email: user.email, password });
  await login();
  const oldCookie = cookie;
  const oldToken = createPersonalAccessToken(user.id, "Old device", "write", { platform: "ios", appVersion: "1" }).token;
  const proof = () => call("/security/reauth", { password });
  const { reauthToken } = (await proof()).body;
  const setup = await call("/security/totp/setup", { reauthToken });
  assert.equal(setup.status, 200);
  assert.match(setup.body.uri, /^otpauth:\/\/totp\//);
  const totp = security.totpFor(setup.body.secret);
  const confirmed = await call("/security/totp/confirm", { challengeId: setup.body.challengeId, code: totp.generate() });
  assert.equal(confirmed.status, 200);
  const codes: string[] = confirmed.body.recoveryCodes;
  assert.equal(codes.length, 10);
  assert.ok(!String((db.prepare("SELECT totp_secret FROM account_security WHERE user_id = ?").get(user.id) as any).totp_secret).includes(setup.body.secret));
  assert.equal(resolveToken(oldToken), null);
  assert.equal((await call("/me", undefined, { cookie: oldCookie })).status, 401);
  assert.equal((await call("/security/totp/confirm", { challengeId: setup.body.challengeId, code: totp.generate() })).status, 400);
  const mfa = await login();
  assert.equal(mfa.status, 403);
  assert.equal(mfa.body.error, "mfa_required");
  assert.equal((await call("/security/mfa", { challengeId: mfa.body.challengeId, code: totp.generate() })).status, 400, "the setup code cannot be replayed");
  assert.equal((await call("/security/mfa", { challengeId: mfa.body.challengeId, code: codes[0] })).status, 200);
  assert.equal((await call("/security/mfa", { challengeId: mfa.body.challengeId, code: codes[1] })).status, 400, "a login challenge works once");
  const again = await login();
  assert.equal((await call("/security/mfa", { challengeId: again.body.challengeId, code: codes[0] })).status, 400, "a recovery code works once");
  assert.equal((await call("/security/mfa", { challengeId: again.body.challengeId, code: codes[1] })).status, 200);
  assert.equal((await call("/security/reauth", { password })).status, 401, "a password alone cannot change MFA");
  assert.equal((await call("/security/totp/disable", { reauthToken })).status, 401, "proof from before enabling MFA is invalid");
  assert.equal((await call("/security/reauth", { password, code: codes[2] }, { origin: "https://evil.example" })).status, 403);
  const token = createPersonalAccessToken(user.id, "Read only", "read", { platform: "ios", appVersion: "1" }).token;
  assert.equal((await call("/security/", undefined, { token })).status, 403);
  const reauthenticated = await call("/security/reauth", { password, code: codes[2] });
  const options = await call("/security/passkeys/register/options", { reauthToken: reauthenticated.body.reauthToken });
  assert.equal(options.status, 200);
  assert.equal(options.body.publicKey.authenticatorSelection.userVerification, "required");
  const { privateKey, publicKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const jwk = publicKey.export({ format: "jwk" });
  const keyId = randomBytes(32);
  const credentialId = keyId.toString("base64url");
  const cose = isoCBOR.encode(new Map<number, unknown>([[1, 2], [3, -7], [-1, 1], [-2, Buffer.from(jwk.x!, "base64url")], [-3, Buffer.from(jwk.y!, "base64url")]]));
  const rpHash = createHash("sha256").update("localhost").digest();
  const length = Buffer.alloc(2); length.writeUInt16BE(keyId.length);
  const authData = Buffer.concat([rpHash, Buffer.from([0x45]), Buffer.alloc(4), Buffer.alloc(16), length, keyId, cose]);
  const client = (type: string, challenge: string, origin = "http://localhost:3000") => Buffer.from(JSON.stringify({ type, challenge, origin }));
  const registration = { id: credentialId, rawId: credentialId, type: "public-key", clientExtensionResults: {}, response: { clientDataJSON: client("webauthn.create", options.body.publicKey.challenge).toString("base64url"), attestationObject: Buffer.from(isoCBOR.encode(new Map<string, unknown>([["fmt", "none"], ["attStmt", new Map()], ["authData", authData]]))).toString("base64url"), transports: ["internal"] } };
  assert.equal((await call("/security/passkeys/register/verify", { challengeId: options.body.challengeId, credential: registration, name: "Test passkey" })).status, 201);
  assert.equal((await call("/security/passkeys/register/verify", { challengeId: options.body.challengeId, credential: registration, name: "Duplicate" })).status, 400);
  async function assertion(overrides: { origin?: string; flags?: number; handle?: string | null; signature?: string; rp?: string; reauth?: boolean } = {}) {
    const challenge = await call(overrides.reauth ? "/security/reauth/passkey/options" : "/security/passkeys/options", {});
    const data = client("webauthn.get", challenge.body.publicKey.challenge, overrides.origin);
    const rp = overrides.rp ? createHash("sha256").update(overrides.rp).digest() : rpHash;
    const authenticator = Buffer.concat([rp, Buffer.from([overrides.flags ?? 5]), Buffer.alloc(4)]);
    const signature = sign("sha256", Buffer.concat([authenticator, createHash("sha256").update(data).digest()]), privateKey).toString("base64url");
    return call(overrides.reauth ? "/security/reauth/passkey/verify" : "/security/passkeys/verify", { challengeId: challenge.body.challengeId, credential: { id: credentialId, rawId: credentialId, type: "public-key", clientExtensionResults: {}, response: { clientDataJSON: data.toString("base64url"), authenticatorData: authenticator.toString("base64url"), signature: overrides.signature ?? signature, userHandle: overrides.handle === undefined ? security.securityAccount(user.id).user_handle : overrides.handle } } });
  }
  assert.equal((await assertion()).status, 200, "a user-verified passkey completes login without TOTP");
  assert.equal((await assertion({ reauth: true, handle: null })).status, 200, "scoped reauthentication may omit userHandle");
  assert.equal((await assertion({ handle: null })).status, 400, "discoverable login requires userHandle");
  assert.equal((await assertion({ origin: "https://evil.example" })).status, 400);
  assert.equal((await assertion({ flags: 1 })).status, 400, "user presence alone is insufficient");
  assert.equal((await assertion({ handle: security.securityAccount(other.id).user_handle })).status, 400);
  assert.equal((await assertion({ rp: "other.example" })).status, 400);
  assert.equal((await assertion({ signature: randomBytes(64).toString("base64url") })).status, 400);
  db.prepare("UPDATE account_security SET totp_secret = ? WHERE user_id = ?").run("unreadable-after-secret-rotation", user.id);
  assert.equal(security.verifySecondFactor(user.id, "123456"), false);
  assert.equal(security.verifySecondFactor(user.id, codes[3]), true, "recovery still works when the encryption secret was rotated");
});
